# Generated by Django 2.2.6 on 2019-10-13 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bikes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=50)),
                ('frame_size', models.PositiveIntegerField()),
                ('used', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Parts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('part_type', models.CharField(max_length=50)),
                ('brand', models.CharField(max_length=50)),
                ('used', models.BooleanField()),
                ('bike_model', models.ManyToManyField(to='deploy_app.Bikes')),
            ],
        ),
        migrations.CreateModel(
            name='Accesories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=50)),
                ('brand', models.CharField(max_length=50)),
                ('bike_model', models.ManyToManyField(to='deploy_app.Bikes')),
                ('part_model', models.ManyToManyField(to='deploy_app.Parts')),
            ],
        ),
    ]
