# Generated by Django 2.2.6 on 2019-10-31 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deploy_app', '0002_auto_20191029_1031'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Brand',
            new_name='Brands',
        ),
    ]
