# Generated by Django 2.2.6 on 2019-10-31 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deploy_app', '0003_auto_20191031_0916'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brands',
            name='title',
        ),
        migrations.AddField(
            model_name='brands',
            name='title',
            field=models.ManyToManyField(to='deploy_app.Bikes'),
        ),
    ]
